### ISSUE TITLE
Suggestions: True full screen mode and child directory support [Enhancement]

### ISSUE THREAD

**Issue by samcsk** [RoyalBingBong/meView#1]
Hi RoyalBingBong,

I just came across this application on the web searching for a solution that can let users to view images, .gifs, .webms and videos with seamless transition in a single package, and meView surprisingly achieve this perfectly. I am really really grateful, but here's some suggestions (shamelessly made by a non-developer):

1. Image switching is blazingly fast, yet the path bar and the seek bar for videos is a bit frustrating in my opinion since I cannot find any option to hide them. It would be able to provide a more immersive experience for it's users if it is possible.

2. For directories that have multiple layers, it seems like it only searches for files in the uppermost layer. I think the code used for viewing archives could be reused to implement this function since in archives it works with the child layers of directories. 

I think this application has great potential and really wish it to have the brightest future, and again, thank you developer, this saves my day.

(I'm on macOS Sierra 10.12.3, using meView v1.2.1)

**Comment by RoyalBingBong** [comment]
> shamelessly made by a non-developer

No shame in that! 😉 

To your suggestions then:

To 1: I actually thought about that before and fully agree with you! I have couple different options in my mind. I was also thinking about reworking the status bar and playback UI, making it smaller and less intrusive.

To 2: I'm deliberately not parsing sub-directories, because that could backfire when a directory has a lot of sub-directories and a lot of files in each. This is also why I have the "folder browser" pop up when you reach the end of a folder. You can use the arrow keys in the folder browser to navigate to all the folders.
It works for archives, because they are handles by a package/library I use to handle zip-support. That library just hands me a list of all files.

Anyway, thank you very much for the feedback!

**Comment by gladstonedigital** [comment]
Could you add a command line switch to enable automatic subdirectory traversal? Something like
```
-r, --recursive
    Opens images from all subdirectories instead of just the top level directory
```
