### ISSUE TITLE
Videos always start muted

### ISSUE THREAD

**Issue by namanj123in** [RoyalBingBong/meView#12]
The video files always seem to start muted even when you uncheck "Mute" in settings. Once you exit the program and start again, the program seems to forget the previous settings.

**Comment by RoyalBingBong** [comment]
Thanks for the bug report.  
I think I fixed it in the 1.5.x version, but lazy me didn't package that version yet :sweat:. I will try to find some time in the upcoming days or the weekend and publish that version as an installer. If you're on Windows or Mac, and if I did everything right with the updater, then meView should automatically update. Otherwise you have to check here later.

**Comment by RoyalBingBong** [comment]
THis should work now in the 1.5.x release.
