### ISSUE TITLE
Command line arguments - specific relative paths not working in 1.4.2

### ISSUE THREAD

**Issue by gladstonedigital** [RoyalBingBong/meView#5]
I saw the code you'd added to fix this bug #3  and seemed like it should work, but I'm still having a similar issue with 1.4.2 to what I was seeing with 1.3.1.

I have a folder structure like:
```
Pictures
 \-- Family
 \-- School
```

If I'm in the folder `Pictures` and run `meview Family`, that works fine, so it's sorta fixed. But if I go into `Pictures/Family` and run `meview .` it doesn't work, just opens nothing. It doesn't seem to recognize the . as meaning current directory.

**Comment by RoyalBingBong** [comment]
As a workaround you can use `meview ./` for now or put the switches befroe the path, e.g. `meview -r .`.

It happens because of [commander](https://github.com/tj/commander.js) and a [workaround](https://github.com/tj/commander.js/issues/512#issuecomment-313176733) I use to make it work properly in my dev environment **and** in the build.
