### ISSUE TITLE
Video / .gifv suggestions

### ISSUE THREAD

**Issue by garygreen** [RoyalBingBong/meView#9]
Great image viewer - I was interested in this because of it's looping video support because I'm in the process of converting all my *.gif to mp4s/gifv. I have a few suggestions:

* In slideshow mode, loop videos so they match the number of seconds for each slide by default. E.g. a slideshow in 15 secs mode, a video of 5 seconds will get played 3 times. A video that's 12 seconds will get played once and the first 3 seconds again before it's cut off and goes onto next slide. Maybe this could be two options for the slideshow mode -
 "Progress to next slide at end of video" and "Play videos in full (could be beyond the slideshow interval)"
* Support the "psuedo" .gifv format. These are basically videos which are intended to be played just like gif - they implicitly mean "loop videos, don't play sounds, and hide controls so it looks like an image/gif"

**Comment by RoyalBingBong** [comment]
* I thought about how I should handle videos in a slideshow and ended up with just playing them in full ignoring the interval time. But I really like your suggestions on that!
* I'm not going to support .gifv, because the "format" is stupid. It's just a plain HTML with some JS, that in the end just loads a .gif or an .mp4 from imgur. Saving a .gifv falsely implicates that you just saved an actual media file like any other image/video on the web, but in reality you just saved a link. The behaviour you mentioned is already in meView.
